// Code generated by MockGen. DO NOT EDIT.
// Source: tokens.go

// Package mock_ast is a generated GoMock package.
package mock_ast

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIast is a mock of Iast interface.
type MockIast struct {
	ctrl     *gomock.Controller
	recorder *MockIastMockRecorder
}

// MockIastMockRecorder is the mock recorder for MockIast.
type MockIastMockRecorder struct {
	mock *MockIast
}

// NewMockIast creates a new mock instance.
func NewMockIast(ctrl *gomock.Controller) *MockIast {
	mock := &MockIast{ctrl: ctrl}
	mock.recorder = &MockIastMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIast) EXPECT() *MockIastMockRecorder {
	return m.recorder
}

// SrsCode mocks base method.
func (m *MockIast) SrsCode() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SrsCode")
	ret0, _ := ret[0].(string)
	return ret0
}

// SrsCode indicates an expected call of SrsCode.
func (mr *MockIastMockRecorder) SrsCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SrsCode", reflect.TypeOf((*MockIast)(nil).SrsCode))
}
