// Code generated by goyacc .\grammar.y. DO NOT EDIT.

//line .\grammar.y:1

package ast

import __yyfmt__ "fmt"

//line .\grammar.y:3

//line .\grammar.y:43
type yySymType struct {
	yys                        int
	token                      Token
	stmt_if                    *IfStatement
	opt_elseif_list            []Statement
	opt_else                   []Statement
	stmt                       Statement
	stmt_loop                  *LoopStatement
	funcProc                   *FunctionOrProcedure
	body                       []Statement
	opt_body                   []Statement
	declarations_method_params []ParamStatement
	declarations_method_param  ParamStatement
	exprs                      []Statement
	opt_export                 *Token
	opt_directive              *Token
	explicit_variables         map[string]VarStatement
	global_variables           []GlobalVariables
	opt_explicit_variables     map[string]VarStatement
	identifiers                []Token
	goToLabel                  *GoToLabelStatement
	opt_goToLabel              *GoToLabelStatement
}

const Directive = 57346
const Identifier = 57347
const Procedure = 57348
const Var = 57349
const EndProcedure = 57350
const If = 57351
const Then = 57352
const ElseIf = 57353
const Else = 57354
const EndIf = 57355
const For = 57356
const Each = 57357
const In = 57358
const To = 57359
const Loop = 57360
const EndLoop = 57361
const Break = 57362
const Not = 57363
const ValueParam = 57364
const While = 57365
const GoToLabel = 57366
const Continue = 57367
const Try = 57368
const Catch = 57369
const EndTry = 57370
const Number = 57371
const String = 57372
const New = 57373
const Function = 57374
const EndFunction = 57375
const Return = 57376
const Throw = 57377
const NeEQ = 57378
const EQUAL = 57379
const LE = 57380
const GE = 57381
const OR = 57382
const And = 57383
const True = 57384
const False = 57385
const Undefind = 57386
const Export = 57387
const Date = 57388
const GoTo = 57389
const Execute = 57390
const UNARMinus = 57391
const UNARYPlus = 57392

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"':'",
	"';'",
	"Directive",
	"Identifier",
	"Procedure",
	"Var",
	"EndProcedure",
	"If",
	"Then",
	"ElseIf",
	"Else",
	"EndIf",
	"For",
	"Each",
	"In",
	"To",
	"Loop",
	"EndLoop",
	"Break",
	"Not",
	"ValueParam",
	"While",
	"GoToLabel",
	"Continue",
	"Try",
	"Catch",
	"EndTry",
	"Number",
	"String",
	"New",
	"Function",
	"EndFunction",
	"Return",
	"Throw",
	"NeEQ",
	"EQUAL",
	"LE",
	"GE",
	"OR",
	"And",
	"True",
	"False",
	"Undefind",
	"Export",
	"Date",
	"GoTo",
	"Execute",
	"'>'",
	"'<'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"UNARMinus",
	"UNARYPlus",
	"'('",
	"')'",
	"'?'",
	"'['",
	"']'",
	"','",
	"'.'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line .\grammar.y:389

//line yacctab:1
var yyExca = [...]int8{
	-1, 0,
	1, 1,
	4, 16,
	5, 16,
	-2, 8,
	-1, 1,
	1, -1,
	-2, 0,
	-1, 2,
	1, 2,
	-2, 17,
	-1, 3,
	8, 8,
	9, 8,
	34, 8,
	-2, 16,
}

const yyPrivate = 57344

const yyLast = 593

var yyAct = [...]uint8{
	7, 5, 49, 193, 116, 45, 157, 145, 132, 17,
	20, 156, 133, 122, 67, 69, 23, 40, 51, 70,
	71, 74, 121, 88, 182, 75, 77, 78, 68, 79,
	137, 136, 83, 84, 63, 60, 64, 65, 61, 62,
	176, 172, 161, 120, 135, 135, 135, 58, 59, 53,
	54, 55, 56, 57, 96, 97, 98, 99, 100, 101,
	102, 103, 104, 105, 106, 107, 108, 63, 60, 64,
	65, 61, 62, 143, 134, 139, 43, 135, 135, 135,
	58, 59, 53, 54, 55, 56, 57, 69, 123, 124,
	69, 110, 126, 134, 135, 58, 59, 53, 54, 55,
	56, 57, 38, 85, 4, 93, 174, 89, 87, 43,
	60, 135, 125, 127, 129, 55, 56, 57, 38, 44,
	42, 69, 58, 59, 53, 54, 55, 56, 57, 150,
	92, 158, 152, 153, 140, 154, 141, 167, 140, 149,
	128, 69, 163, 138, 178, 148, 37, 166, 159, 160,
	165, 140, 44, 95, 162, 201, 86, 195, 91, 52,
	51, 168, 53, 54, 55, 56, 57, 179, 72, 173,
	117, 183, 175, 173, 52, 51, 177, 131, 188, 155,
	185, 184, 189, 190, 186, 187, 119, 118, 112, 51,
	207, 82, 80, 41, 43, 200, 199, 197, 24, 115,
	202, 203, 73, 25, 130, 206, 205, 6, 208, 12,
	19, 46, 26, 42, 11, 27, 169, 81, 30, 29,
	38, 52, 51, 14, 13, 52, 51, 52, 51, 52,
	51, 33, 34, 36, 181, 35, 21, 44, 198, 43,
	32, 31, 192, 24, 191, 3, 170, 18, 25, 39,
	1, 171, 52, 51, 12, 19, 15, 26, 42, 11,
	27, 146, 50, 30, 29, 38, 52, 51, 14, 13,
	52, 51, 204, 48, 43, 10, 33, 34, 36, 194,
	35, 21, 44, 22, 76, 32, 31, 47, 2, 147,
	19, 90, 18, 42, 39, 28, 66, 94, 30, 29,
	38, 164, 8, 16, 9, 0, 43, 0, 0, 0,
	0, 33, 34, 36, 0, 35, 21, 44, 0, 0,
	32, 31, 19, 0, 60, 42, 65, 18, 0, 39,
	30, 29, 38, 0, 0, 0, 58, 59, 53, 54,
	55, 56, 57, 33, 34, 36, 0, 35, 21, 44,
	0, 0, 32, 31, 0, 63, 60, 64, 65, 18,
	62, 39, 63, 60, 64, 65, 61, 62, 58, 59,
	53, 54, 55, 56, 57, 58, 59, 53, 54, 55,
	56, 57, 63, 60, 64, 65, 61, 62, 142, 0,
	0, 0, 0, 0, 0, 58, 59, 53, 54, 55,
	56, 57, 0, 0, 0, 196, 63, 60, 64, 65,
	61, 62, 0, 0, 0, 0, 0, 0, 0, 58,
	59, 53, 54, 55, 56, 57, 0, 0, 180, 144,
	63, 60, 64, 65, 61, 62, 0, 0, 0, 0,
	0, 0, 0, 58, 59, 53, 54, 55, 56, 57,
	0, 0, 0, 109, 63, 60, 64, 65, 61, 62,
	151, 0, 0, 0, 0, 0, 0, 58, 59, 53,
	54, 55, 56, 57, 0, 0, 0, 0, 63, 60,
	64, 65, 61, 62, 114, 0, 0, 0, 0, 0,
	113, 58, 59, 53, 54, 55, 56, 57, 0, 0,
	0, 0, 63, 60, 64, 65, 61, 62, 111, 63,
	60, 64, 65, 61, 62, 58, 59, 53, 54, 55,
	56, 57, 58, 59, 53, 54, 55, 56, 57, 0,
	0, 0, 0, 0, 63, 60, 64, 65, 61, 62,
	0, 63, 60, 64, 65, 0, 0, 58, 59, 53,
	54, 55, 56, 57, 58, 59, 53, 54, 55, 56,
	57, 60, 64, 65, 42, 0, 0, 0, 0, 30,
	29, 0, 0, 58, 59, 53, 54, 55, 56, 57,
	0, 0, 33, 34, 36, 0, 35, 0, 0, 0,
	0, 32, 31,
}

var yyPact = [...]int16{
	187, -1000, -1000, 187, -1000, 266, -1000, -4, -1000, -1000,
	-1000, -1000, -1000, 299, 299, -1000, -1000, -1000, 299, 299,
	-1000, 94, -1000, -45, 299, 267, 299, 232, 183, -1000,
	-1000, 299, 299, -1000, -1000, -1000, -1000, -1000, 96, 48,
	-40, -1000, -1000, 47, 98, 266, -1000, -1000, 232, -1000,
	-1000, -1000, -1000, 299, 299, 299, 299, 299, 299, 299,
	299, 299, 299, 299, 299, 299, -1000, -4, -1000, -4,
	392, 71, -1000, 102, -1000, 496, 181, 471, 464, 170,
	163, 180, 179, -1000, -1000, -17, 299, 299, 299, 299,
	-1000, 299, -1000, -1000, -1000, -1000, 60, 60, -1000, -1000,
	-1000, 109, 109, 44, 317, 503, 522, 285, 71, -1000,
	-40, 232, 122, 299, -1000, -1000, 46, -1000, -29, -30,
	299, 14, -1000, 29, 324, 12, 368, 248, 69, 440,
	232, 232, 184, 172, -1000, -1000, 124, 124, -19, -1000,
	299, 299, -1000, -1000, -1000, 136, 299, 117, -45, -1000,
	85, -1000, 225, 221, -1000, -1000, -20, 67, -1000, 165,
	-21, -1000, -1000, 29, 129, 232, 416, -1000, -37, 232,
	-1000, -1000, 27, 124, 538, -1000, 27, 299, -1000, 266,
	232, 232, -1000, 223, -1000, 67, -1000, 148, 344, 248,
	217, -1000, 148, 232, 146, 163, -1000, -1000, -1000, 232,
	262, 163, 13, 155, -1000, 13, -1000, -1000, -1000,
}

var yyPgo = [...]int16{
	0, 287, 1, 104, 304, 303, 302, 7, 301, 297,
	296, 22, 0, 8, 295, 9, 11, 6, 13, 291,
	16, 289, 10, 283, 3, 279, 4, 275, 17, 146,
	273, 2, 262, 256, 250, 245, 207, 242, 12, 234,
	216, 204, 202, 177,
}

var yyR1 = [...]int8{
	0, 34, 34, 34, 35, 35, 36, 36, 14, 14,
	13, 13, 33, 37, 5, 5, 2, 2, 1, 1,
	9, 9, 30, 30, 24, 24, 25, 25, 6, 7,
	7, 8, 8, 23, 39, 4, 40, 4, 41, 4,
	21, 21, 21, 3, 3, 3, 3, 3, 3, 3,
	3, 10, 10, 20, 20, 28, 28, 28, 28, 28,
	19, 19, 43, 27, 12, 12, 12, 12, 12, 12,
	12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
	12, 12, 12, 12, 18, 18, 17, 17, 17, 16,
	16, 16, 22, 22, 22, 15, 15, 15, 15, 15,
	15, 15, 15, 15, 29, 11, 11, 26, 26, 31,
	32, 38, 42,
}

var yyR2 = [...]int8{
	0, 0, 1, 2, 1, 2, 1, 1, 0, 1,
	0, 1, 5, 0, 11, 10, 0, 1, 1, 3,
	0, 1, 1, 1, 0, 1, 3, 4, 7, 0,
	5, 0, 2, 8, 0, 9, 0, 8, 0, 6,
	1, 1, 3, 1, 1, 1, 1, 1, 1, 2,
	2, 0, 1, 1, 3, 1, 4, 4, 2, 4,
	1, 1, 0, 6, 1, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 2,
	1, 2, 1, 1, 0, 1, 1, 2, 3, 0,
	1, 3, 2, 5, 4, 1, 1, 2, 2, 1,
	1, 1, 1, 1, 1, 1, 3, 1, 3, 1,
	1, 1, 1,
}

var yyChk = [...]int16{
	-1000, -34, -1, -35, -3, -2, -36, -12, -6, -4,
	-27, 27, 22, 37, 36, -33, -5, -15, 60, 23,
	-22, 49, -23, -20, 11, 16, 25, 28, -14, 32,
	31, 54, 53, 44, 45, 48, 46, -29, 33, 62,
	-28, 6, 26, 7, 50, -2, -36, -1, -30, -31,
	-32, 5, 4, 53, 54, 55, 56, 57, 51, 52,
	39, 42, 43, 38, 40, 41, -10, -12, -18, -12,
	-12, -12, -29, -42, 66, -12, 17, -12, -12, -2,
	9, 34, 8, -12, -12, 7, 60, 60, 63, 60,
	-19, 60, 32, 7, -9, -3, -12, -12, -12, -12,
	-12, -12, -12, -12, -12, -12, -12, -12, -12, 61,
	-28, 12, 7, 19, 20, 29, -26, 7, 7, 7,
	60, -11, -18, -12, -12, -11, -12, -2, 18, -12,
	-41, -43, -13, -38, 47, 65, 60, 60, -11, 61,
	-38, -38, 64, 61, 61, -7, 13, -21, -20, -22,
	60, 20, -2, -2, -31, 7, -16, -17, 7, 24,
	-16, 61, -18, -12, -8, 14, -12, 20, -22, -40,
	21, 30, 61, -38, 39, 7, 61, -38, 15, -2,
	12, -39, 61, -2, -13, -17, -15, -13, -12, -2,
	-2, 21, -37, -24, -25, 9, 61, -7, 21, -24,
	-2, 9, -26, -2, 10, -26, -31, 35, -31,
}

var yyDef = [...]int8{
	-2, -2, -2, -2, 18, 0, 4, 43, 44, 45,
	46, 47, 48, 51, 84, 6, 7, 64, 0, 0,
	80, 0, 82, 83, 0, 0, 0, 16, 0, 95,
	96, 0, 0, 99, 100, 101, 102, 103, 0, 0,
	53, 9, 104, 55, 0, 3, 5, 17, 20, 22,
	23, 109, 110, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 49, 52, 50, 85,
	0, 79, 81, 0, 112, 0, 0, 0, 0, 0,
	0, 0, 0, 97, 98, 92, 84, 0, 0, 84,
	58, 0, 60, 61, 19, 21, 66, 67, 68, 69,
	70, 71, 72, 73, 74, 75, 76, 77, 78, 65,
	54, 16, 0, 0, 38, 62, 10, 107, 0, 0,
	84, 0, 105, 0, 0, 0, 0, 29, 0, 0,
	16, 16, 0, 0, 11, 111, 89, 89, 0, 94,
	84, 0, 57, 56, 59, 31, 0, 0, 40, 41,
	0, 36, 0, 0, 12, 108, 0, 90, 86, 0,
	0, 93, 106, 0, 0, 16, 0, 34, 0, 16,
	39, 63, 10, 0, 0, 87, 10, 0, 28, 32,
	16, 16, 42, 0, 13, 91, 88, 24, 0, 29,
	0, 37, 24, 16, 25, 0, 33, 30, 35, 16,
	0, 0, 0, 0, 15, 0, 26, 14, 27,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 57, 3, 3,
	60, 61, 55, 53, 65, 54, 66, 56, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 4, 5,
	52, 3, 51, 62, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 63, 3, 64,
}

var yyTok2 = [...]int8{
	2, 3, 6, 7, 8, 9, 10, 11, 12, 13,
	14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
	24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
	34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
	44, 45, 46, 47, 48, 49, 50, 58, 59,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-0 : yypt+1]
//line .\grammar.y:89
		{
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:90
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[1].body, yylex)
			}
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line .\grammar.y:95
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[2].opt_body, yylex)
			}
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:105
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[1].global_variables, yylex)
			}
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:110
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[1].funcProc, yylex)
			}
		}
	case 8:
		yyDollar = yyS[yypt-0 : yypt+1]
//line .\grammar.y:117
		{
			yyVAL.opt_directive = nil
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:118
		{
			yyVAL.opt_directive = &yyDollar[1].token
		}
	case 10:
		yyDollar = yyS[yypt-0 : yypt+1]
//line .\grammar.y:121
		{
			yyVAL.opt_export = nil
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:122
		{
			yyVAL.opt_export = &yyDollar[1].token
		}
	case 12:
		yyDollar = yyS[yypt-5 : yypt+1]
//line .\grammar.y:125
		{
			yyVAL.global_variables = make([]GlobalVariables, len(yyDollar[3].identifiers), len(yyDollar[3].identifiers))
			for i, v := range yyDollar[3].identifiers {
				if yyDollar[1].opt_directive != nil {
					yyVAL.global_variables[i].Directive = yyDollar[1].opt_directive.literal
				}

				yyVAL.global_variables[i].Export = yyDollar[4].opt_export != nil
				yyVAL.global_variables[i].Var = VarStatement{Name: v.literal}
			}
		}
	case 13:
		yyDollar = yyS[yypt-7 : yypt+1]
//line .\grammar.y:138
		{
			isFunction(true, yylex)
		}
	case 14:
		yyDollar = yyS[yypt-11 : yypt+1]
//line .\grammar.y:139
		{
			yyVAL.funcProc = createFunctionOrProcedure(PFTypeFunction, yyDollar[1].opt_directive, yyDollar[3].token.literal, yyDollar[5].declarations_method_params, yyDollar[7].opt_export, yyDollar[9].opt_explicit_variables, yyDollar[10].opt_body)
			isFunction(false, yylex)
		}
	case 15:
		yyDollar = yyS[yypt-10 : yypt+1]
//line .\grammar.y:144
		{
			yyVAL.funcProc = createFunctionOrProcedure(PFTypeProcedure, yyDollar[1].opt_directive, yyDollar[3].token.literal, yyDollar[5].declarations_method_params, yyDollar[7].opt_export, yyDollar[8].opt_explicit_variables, yyDollar[9].opt_body)
		}
	case 16:
		yyDollar = yyS[yypt-0 : yypt+1]
//line .\grammar.y:149
		{
			yyVAL.opt_body = nil
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:150
		{
			yyVAL.opt_body = yyDollar[1].body
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:154
		{
			if ast, ok := yylex.(*AstNode); ok {
				yyVAL.body = []Statement{ast.statementPostProcessing(yyDollar[1].stmt)}
			} else {
				yyVAL.body = []Statement{yyDollar[1].stmt}
			}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:161
		{
			if yyDollar[2].token.literal == ":" && len(yyDollar[1].opt_body) > 0 {
				if _, ok := yyDollar[1].opt_body[len(yyDollar[1].opt_body)-1].(*GoToLabelStatement); !ok {
					yylex.Error("semicolon (;) is expected")
				}
			}
			if yyDollar[3].stmt != nil {
				yyVAL.body = append(yyVAL.body, yyDollar[3].stmt)
			}
		}
	case 20:
		yyDollar = yyS[yypt-0 : yypt+1]
//line .\grammar.y:174
		{
			yyVAL.stmt = nil
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:175
		{
			if ast, ok := yylex.(*AstNode); ok {
				yyVAL.stmt = ast.statementPostProcessing(yyDollar[1].stmt)
			} else {
				yyVAL.stmt = yyDollar[1].stmt
			}
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:184
		{
			yyVAL.token = yyDollar[1].token
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:184
		{
			yyVAL.token = yyDollar[1].token
		}
	case 24:
		yyDollar = yyS[yypt-0 : yypt+1]
//line .\grammar.y:188
		{
			yyVAL.opt_explicit_variables = map[string]VarStatement{}
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:189
		{
			yyVAL.opt_explicit_variables = yyDollar[1].explicit_variables
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:192
		{
			if vars, err := appendVarStatements(map[string]VarStatement{}, yyDollar[2].identifiers); err != nil {
				yylex.Error(err.Error())
			} else {
				yyVAL.explicit_variables = vars
			}
		}
	case 27:
		yyDollar = yyS[yypt-4 : yypt+1]
//line .\grammar.y:199
		{
			if vars, err := appendVarStatements(yyDollar[1].explicit_variables, yyDollar[3].identifiers); err != nil {
				yylex.Error(err.Error())
			} else {
				yyVAL.explicit_variables = vars
			}
		}
	case 28:
		yyDollar = yyS[yypt-7 : yypt+1]
//line .\grammar.y:210
		{
			yyVAL.stmt_if = &IfStatement{
				Expression:  yyDollar[2].stmt,
				TrueBlock:   yyDollar[4].opt_body,
				IfElseBlock: yyDollar[5].opt_elseif_list,
				ElseBlock:   yyDollar[6].opt_else,
			}
		}
	case 29:
		yyDollar = yyS[yypt-0 : yypt+1]
//line .\grammar.y:220
		{
			yyVAL.opt_elseif_list = []Statement{}
		}
	case 30:
		yyDollar = yyS[yypt-5 : yypt+1]
//line .\grammar.y:221
		{
			yyVAL.opt_elseif_list = append(yyDollar[5].opt_elseif_list, &IfStatement{
				Expression: yyDollar[2].stmt,
				TrueBlock:  yyDollar[4].opt_body,
			})
		}
	case 31:
		yyDollar = yyS[yypt-0 : yypt+1]
//line .\grammar.y:229
		{
			yyVAL.opt_else = nil
		}
	case 32:
		yyDollar = yyS[yypt-2 : yypt+1]
//line .\grammar.y:230
		{
			yyVAL.opt_else = yyDollar[2].opt_body
		}
	case 33:
		yyDollar = yyS[yypt-8 : yypt+1]
//line .\grammar.y:233
		{
			yyVAL.stmt = TernaryStatement{
				Expression: yyDollar[3].stmt,
				TrueBlock:  yyDollar[5].stmt,
				ElseBlock:  yyDollar[7].stmt,
			}
		}
	case 34:
		yyDollar = yyS[yypt-6 : yypt+1]
//line .\grammar.y:242
		{
			setLoopFlag(true, yylex)
		}
	case 35:
		yyDollar = yyS[yypt-9 : yypt+1]
//line .\grammar.y:242
		{
			yyVAL.stmt_loop = &LoopStatement{
				For:  yyDollar[3].token.literal,
				In:   yyDollar[5].stmt,
				Body: yyDollar[8].opt_body,
			}
			setLoopFlag(false, yylex)
		}
	case 36:
		yyDollar = yyS[yypt-5 : yypt+1]
//line .\grammar.y:250
		{
			setLoopFlag(true, yylex)
		}
	case 37:
		yyDollar = yyS[yypt-8 : yypt+1]
//line .\grammar.y:250
		{
			yyVAL.stmt_loop = &LoopStatement{
				For:  yyDollar[2].stmt,
				To:   yyDollar[4].stmt,
				Body: yyDollar[7].opt_body,
			}
			setLoopFlag(false, yylex)
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:258
		{
			setLoopFlag(true, yylex)
		}
	case 39:
		yyDollar = yyS[yypt-6 : yypt+1]
//line .\grammar.y:258
		{
			yyVAL.stmt_loop = &LoopStatement{
				WhileExpr: yyDollar[2].stmt,
				Body:      yyDollar[5].opt_body,
			}
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:267
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:268
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:269
		{
			yyVAL.stmt = yyDollar[2].stmt
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:272
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:273
		{
			yyVAL.stmt = yyDollar[1].stmt_if
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:274
		{
			yyVAL.stmt = yyDollar[1].stmt_loop
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:275
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:276
		{
			yyVAL.stmt = ContinueStatement{}
			checkLoopOperator(yyDollar[1].token, yylex)
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:277
		{
			yyVAL.stmt = BreakStatement{}
			checkLoopOperator(yyDollar[1].token, yylex)
		}
	case 49:
		yyDollar = yyS[yypt-2 : yypt+1]
//line .\grammar.y:278
		{
			yyVAL.stmt = ThrowStatement{Param: yyDollar[2].stmt}
			checkThrowParam(yyDollar[1].token, yyDollar[2].stmt, yylex)
		}
	case 50:
		yyDollar = yyS[yypt-2 : yypt+1]
//line .\grammar.y:279
		{
			yyVAL.stmt = &ReturnStatement{Param: yyDollar[2].stmt}
			checkReturnParam(yyDollar[2].stmt, yylex)
		}
	case 51:
		yyDollar = yyS[yypt-0 : yypt+1]
//line .\grammar.y:282
		{
			yyVAL.stmt = nil
		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:283
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:288
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:289
		{
			yyVAL.stmt = CallChainStatement{Unit: yyDollar[3].stmt, Call: yyDollar[1].stmt}
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:295
		{
			yyVAL.stmt = VarStatement{Name: yyDollar[1].token.literal}
		}
	case 56:
		yyDollar = yyS[yypt-4 : yypt+1]
//line .\grammar.y:296
		{
			yyVAL.stmt = MethodStatement{Name: yyDollar[1].token.literal, Param: yyDollar[3].exprs}
		}
	case 57:
		yyDollar = yyS[yypt-4 : yypt+1]
//line .\grammar.y:297
		{
			yyVAL.stmt = ItemStatement{Object: yyDollar[1].stmt, Item: yyDollar[3].stmt}
		}
	case 58:
		yyDollar = yyS[yypt-2 : yypt+1]
//line .\grammar.y:298
		{
			yyVAL.stmt = MethodStatement{Name: yyDollar[1].token.literal, Param: []Statement{yyDollar[2].stmt}}
		}
	case 59:
		yyDollar = yyS[yypt-4 : yypt+1]
//line .\grammar.y:299
		{
			yyVAL.stmt = MethodStatement{Name: yyDollar[1].token.literal, Param: []Statement{yyDollar[3].stmt}}
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:302
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:303
		{
			yyVAL.stmt = VarStatement{Name: yyDollar[1].token.literal}
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:306
		{
			setTryFlag(true, yylex)
		}
	case 63:
		yyDollar = yyS[yypt-6 : yypt+1]
//line .\grammar.y:306
		{
			yyVAL.stmt = TryStatement{Body: yyDollar[2].opt_body, Catch: yyDollar[5].opt_body}
			setTryFlag(false, yylex)
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:312
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:313
		{
			yyVAL.stmt = yyDollar[2].stmt
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:314
		{
			yyVAL.stmt = &ExpStatement{Operation: OpPlus, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 67:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:315
		{
			yyVAL.stmt = &ExpStatement{Operation: OpMinus, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:316
		{
			yyVAL.stmt = &ExpStatement{Operation: OpMul, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:317
		{
			yyVAL.stmt = &ExpStatement{Operation: OpDiv, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 70:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:318
		{
			yyVAL.stmt = &ExpStatement{Operation: OpMod, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:319
		{
			yyVAL.stmt = &ExpStatement{Operation: OpGt, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:320
		{
			yyVAL.stmt = &ExpStatement{Operation: OpLt, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 73:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:321
		{
			yyVAL.stmt = &ExpStatement{Operation: OpEq, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:322
		{
			yyVAL.stmt = &ExpStatement{Operation: OpOr, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:323
		{
			yyVAL.stmt = &ExpStatement{Operation: OpAnd, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 76:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:324
		{
			yyVAL.stmt = &ExpStatement{Operation: OpNe, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:325
		{
			yyVAL.stmt = &ExpStatement{Operation: OpLe, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:326
		{
			yyVAL.stmt = &ExpStatement{Operation: OpGe, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 79:
		yyDollar = yyS[yypt-2 : yypt+1]
//line .\grammar.y:327
		{
			yyVAL.stmt = not(yyDollar[2].stmt)
		}
	case 80:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:328
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 81:
		yyDollar = yyS[yypt-2 : yypt+1]
//line .\grammar.y:329
		{
			yyVAL.stmt = GoToStatement{Label: yyDollar[2].goToLabel}
		}
	case 82:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:330
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 83:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:331
		{
			if tok, ok := yyDollar[1].stmt.(Token); ok {
				yyVAL.stmt = tok.literal
			} else {
				yyVAL.stmt = yyDollar[1].stmt
			}
		}
	case 84:
		yyDollar = yyS[yypt-0 : yypt+1]
//line .\grammar.y:340
		{
			yyVAL.stmt = nil
		}
	case 85:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:340
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 86:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:343
		{
			yyVAL.declarations_method_param = *(&ParamStatement{}).Fill(nil, yyDollar[1].token)
		}
	case 87:
		yyDollar = yyS[yypt-2 : yypt+1]
//line .\grammar.y:344
		{
			yyVAL.declarations_method_param = *(&ParamStatement{}).Fill(&yyDollar[1].token, yyDollar[2].token)
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:345
		{
			yyVAL.declarations_method_param = *(yyVAL.declarations_method_param.DefaultValue(yyDollar[3].stmt))
		}
	case 89:
		yyDollar = yyS[yypt-0 : yypt+1]
//line .\grammar.y:348
		{
			yyVAL.declarations_method_params = []ParamStatement{}
		}
	case 90:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:349
		{
			yyVAL.declarations_method_params = []ParamStatement{yyDollar[1].declarations_method_param}
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:350
		{
			yyVAL.declarations_method_params = append(yyDollar[1].declarations_method_params, yyDollar[3].declarations_method_param)
		}
	case 92:
		yyDollar = yyS[yypt-2 : yypt+1]
//line .\grammar.y:358
		{
			yyVAL.stmt = NewObjectStatement{Constructor: yyDollar[2].token.literal}
		}
	case 93:
		yyDollar = yyS[yypt-5 : yypt+1]
//line .\grammar.y:359
		{
			yyVAL.stmt = NewObjectStatement{Constructor: yyDollar[2].token.literal, Param: yyDollar[4].exprs}
		}
	case 94:
		yyDollar = yyS[yypt-4 : yypt+1]
//line .\grammar.y:360
		{
			yyVAL.stmt = NewObjectStatement{Param: yyDollar[3].exprs}
		}
	case 95:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:363
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:364
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 97:
		yyDollar = yyS[yypt-2 : yypt+1]
//line .\grammar.y:365
		{
			yyVAL.stmt = unaryMinus(yyDollar[2].stmt)
		}
	case 98:
		yyDollar = yyS[yypt-2 : yypt+1]
//line .\grammar.y:366
		{
			yyVAL.stmt = yyDollar[2].stmt
		}
	case 99:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:367
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 100:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:368
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 101:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:369
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 102:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:370
		{
			yyVAL.stmt = UndefinedStatement{}
		}
	case 103:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:371
		{
			yyVAL.stmt = yyDollar[1].goToLabel
		}
	case 104:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:374
		{
			yyVAL.goToLabel = &GoToLabelStatement{Name: yyDollar[1].token.literal}
		}
	case 105:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:376
		{
			yyVAL.exprs = []Statement{yyDollar[1].stmt}
		}
	case 106:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:377
		{
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].stmt)
		}
	case 107:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:380
		{
			yyVAL.identifiers = []Token{yyDollar[1].token}
		}
	case 108:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:381
		{
			yyVAL.identifiers = append(yyVAL.identifiers, yyDollar[3].token)
		}
	case 109:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:384
		{
			yyVAL.token = yyDollar[1].token
		}
	case 110:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:385
		{
			yyVAL.token = yyDollar[1].token
		}
	}
	goto yystack /* stack new state and value */
}
