// Code generated by goyacc .\grammar.y. DO NOT EDIT.

//line .\grammar.y:1

package ast

import __yyfmt__ "fmt"

//line .\grammar.y:3

//line .\grammar.y:42
type yySymType struct {
	yys                        int
	token                      Token
	stmt_if                    *IfStatement
	opt_elseif_list            Statements
	opt_else                   Statements
	stmt                       Statement
	stmt_loop                  *LoopStatement
	funcProc                   *FunctionOrProcedure
	body                       Statements
	opt_body                   Statements
	declarations_method_params []ParamStatement
	declarations_method_param  ParamStatement
	exprs                      ExprStatements
	opt_export                 *Token
	opt_directive              *Token
	explicit_variables         map[string]VarStatement
	global_variables           []GlobalVariables
	opt_explicit_variables     map[string]VarStatement
	identifiers                []Token
	goToLabel                  *GoToLabelStatement
	opt_goToLabel              *GoToLabelStatement
}

const Directive = 57346
const token_identifier = 57347
const Procedure = 57348
const Var = 57349
const EndProcedure = 57350
const If = 57351
const Then = 57352
const ElseIf = 57353
const Else = 57354
const EndIf = 57355
const For = 57356
const Each = 57357
const In = 57358
const To = 57359
const Loop = 57360
const EndLoop = 57361
const Break = 57362
const Not = 57363
const ValueParam = 57364
const While = 57365
const GoToLabel = 57366
const Continue = 57367
const Try = 57368
const Catch = 57369
const EndTry = 57370
const Number = 57371
const String = 57372
const New = 57373
const Function = 57374
const EndFunction = 57375
const Return = 57376
const Throw = 57377
const NeEQ = 57378
const EQUAL = 57379
const LE = 57380
const GE = 57381
const OR = 57382
const And = 57383
const True = 57384
const False = 57385
const Undefind = 57386
const Export = 57387
const Date = 57388
const GoTo = 57389
const Execute = 57390
const LOW_PREC = 57391
const UNARMinus = 57392
const UNARYPlus = 57393

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"':'",
	"';'",
	"','",
	"Directive",
	"token_identifier",
	"Procedure",
	"Var",
	"EndProcedure",
	"If",
	"Then",
	"ElseIf",
	"Else",
	"EndIf",
	"For",
	"Each",
	"In",
	"To",
	"Loop",
	"EndLoop",
	"Break",
	"Not",
	"ValueParam",
	"While",
	"GoToLabel",
	"Continue",
	"Try",
	"Catch",
	"EndTry",
	"Number",
	"String",
	"New",
	"Function",
	"EndFunction",
	"Return",
	"Throw",
	"NeEQ",
	"EQUAL",
	"LE",
	"GE",
	"OR",
	"And",
	"True",
	"False",
	"Undefind",
	"Export",
	"Date",
	"GoTo",
	"Execute",
	"LOW_PREC",
	"'>'",
	"'<'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"UNARMinus",
	"UNARYPlus",
	"'('",
	"')'",
	"'?'",
	"'['",
	"']'",
	"'.'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line .\grammar.y:373

//line yacctab:1
var yyExca = [...]int8{
	-1, 0,
	1, 1,
	4, 16,
	5, 16,
	-2, 8,
	-1, 1,
	1, -1,
	-2, 0,
	-1, 2,
	1, 2,
	-2, 17,
	-1, 3,
	9, 8,
	10, 8,
	35, 8,
	-2, 16,
}

const yyPrivate = 57344

const yyLast = 574

var yyAct = [...]uint8{
	114, 8, 5, 122, 49, 195, 45, 148, 138, 21,
	159, 18, 41, 160, 24, 72, 69, 69, 77, 91,
	184, 69, 74, 73, 88, 142, 141, 78, 80, 81,
	62, 82, 67, 115, 86, 87, 126, 115, 68, 71,
	54, 90, 140, 60, 61, 55, 56, 57, 58, 59,
	115, 115, 176, 115, 39, 98, 69, 100, 101, 102,
	103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
	99, 60, 61, 55, 56, 57, 58, 59, 89, 70,
	43, 53, 65, 62, 66, 67, 63, 64, 115, 116,
	178, 69, 128, 129, 174, 130, 60, 61, 55, 56,
	57, 58, 59, 54, 115, 127, 169, 164, 144, 146,
	131, 70, 57, 58, 59, 134, 69, 62, 66, 67,
	133, 135, 44, 139, 85, 83, 4, 180, 69, 145,
	60, 61, 55, 56, 57, 58, 59, 39, 132, 155,
	156, 167, 143, 157, 152, 113, 140, 165, 95, 151,
	84, 168, 161, 163, 44, 55, 56, 57, 58, 59,
	175, 38, 203, 170, 175, 153, 179, 197, 123, 162,
	181, 52, 51, 94, 185, 97, 177, 65, 62, 66,
	67, 190, 64, 186, 75, 191, 192, 189, 188, 187,
	158, 60, 61, 55, 56, 57, 58, 59, 202, 199,
	201, 204, 93, 209, 205, 139, 125, 207, 139, 208,
	42, 7, 210, 52, 51, 25, 52, 51, 52, 51,
	26, 124, 51, 118, 52, 51, 13, 20, 149, 27,
	43, 12, 28, 52, 51, 31, 30, 39, 137, 121,
	15, 14, 200, 173, 52, 51, 51, 115, 34, 35,
	37, 193, 36, 22, 44, 52, 51, 7, 33, 32,
	76, 25, 172, 52, 51, 19, 26, 40, 47, 2,
	206, 136, 13, 20, 171, 27, 43, 12, 28, 183,
	6, 31, 30, 39, 46, 194, 15, 14, 3, 1,
	16, 70, 50, 48, 34, 35, 37, 11, 36, 22,
	44, 79, 196, 23, 33, 32, 150, 20, 92, 29,
	43, 19, 96, 40, 166, 31, 30, 39, 9, 17,
	10, 0, 0, 0, 70, 0, 0, 0, 34, 35,
	37, 0, 36, 22, 44, 0, 0, 0, 33, 32,
	20, 62, 0, 43, 0, 19, 0, 40, 31, 30,
	39, 0, 0, 0, 60, 61, 55, 56, 57, 58,
	59, 34, 35, 37, 0, 36, 22, 44, 0, 0,
	0, 33, 32, 65, 62, 66, 67, 0, 19, 0,
	40, 65, 62, 66, 67, 63, 64, 60, 61, 55,
	56, 57, 58, 59, 0, 60, 61, 55, 56, 57,
	58, 59, 0, 0, 0, 198, 65, 62, 66, 67,
	63, 64, 182, 115, 0, 0, 0, 0, 0, 0,
	60, 61, 55, 56, 57, 58, 59, 0, 0, 0,
	147, 0, 0, 0, 0, 0, 0, 0, 65, 62,
	66, 67, 63, 64, 0, 0, 65, 62, 66, 67,
	63, 64, 60, 61, 55, 56, 57, 58, 59, 154,
	60, 61, 55, 56, 57, 58, 59, 120, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 65, 62, 66,
	67, 63, 64, 117, 0, 65, 62, 66, 67, 63,
	64, 60, 61, 55, 56, 57, 58, 59, 119, 60,
	61, 55, 56, 57, 58, 59, 0, 0, 0, 65,
	62, 66, 67, 63, 64, 0, 0, 65, 62, 66,
	67, 63, 64, 60, 61, 55, 56, 57, 58, 59,
	0, 60, 61, 55, 56, 57, 58, 59, 65, 62,
	66, 67, 63, 64, 43, 0, 0, 0, 0, 31,
	30, 0, 60, 61, 55, 56, 57, 58, 59, 0,
	0, 0, 34, 35, 37, 0, 36, 0, 0, 0,
	0, 0, 33, 32,
}

var yyPact = [...]int16{
	203, -1000, -1000, 203, -1000, 251, -1000, 41, 499, -1000,
	-1000, -1000, -1000, -1000, 316, 316, -1000, -1000, -1000, 316,
	316, -1000, 53, -1000, -49, 316, 283, 316, 249, 115,
	-1000, -1000, 316, 316, -1000, -1000, -1000, -1000, -1000, 16,
	-21, -46, -1000, -1000, 140, 251, -1000, -1000, 249, -1000,
	-1000, -1000, -1000, 316, 316, 316, 316, 316, 316, 316,
	316, 316, 316, 316, 316, 316, 316, 316, -1000, 499,
	-22, -1000, 82, -1000, 301, -1000, 71, -1000, 470, 215,
	478, 446, 209, 160, 213, 198, -1000, -1000, -26, 316,
	316, 316, -1000, 316, -1000, -1000, -1000, -1000, 499, 47,
	55, 55, -1000, -1000, -1000, 100, 100, 18, 138, 334,
	77, -10, 301, -1000, 316, -1000, -46, 249, 96, 316,
	-1000, -1000, 98, -1000, -36, -37, 316, 45, 407, 43,
	367, -1000, -1000, 214, 103, 438, 249, 249, 217, 182,
	-1000, 144, 144, 44, -1000, 316, -1000, -1000, 126, 316,
	85, -49, -1000, 20, -1000, 240, 212, -1000, -1000, 31,
	12, -1000, 168, 27, -1000, 407, 111, 249, 399, -1000,
	-43, 249, -1000, -1000, -6, 144, 517, -1000, -6, 316,
	-1000, 251, 249, 249, -1000, 229, -1000, 12, -1000, 157,
	342, 214, 220, -1000, 157, 249, 152, 160, -1000, -1000,
	-1000, 249, 259, 160, 241, 167, -1000, 241, -1000, -1000,
	-1000,
}

var yyPgo = [...]int16{
	0, 268, 2, 126, 320, 319, 318, 7, 314, 312,
	15, 1, 8, 309, 11, 10, 13, 23, 308, 14,
	306, 9, 303, 5, 302, 3, 297, 12, 161, 293,
	4, 292, 290, 0, 289, 288, 280, 285, 279, 274,
	271, 260, 238,
}

var yyR1 = [...]int8{
	0, 34, 34, 34, 35, 35, 36, 36, 13, 13,
	12, 12, 32, 37, 5, 5, 2, 2, 1, 1,
	9, 9, 29, 29, 23, 23, 24, 24, 6, 7,
	7, 8, 8, 22, 38, 4, 39, 4, 40, 4,
	20, 20, 20, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 19, 19, 27, 27, 27, 27, 27, 18,
	18, 42, 26, 11, 11, 11, 11, 11, 11, 11,
	11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
	11, 11, 11, 17, 17, 10, 10, 14, 14, 14,
	14, 14, 14, 14, 14, 14, 16, 16, 16, 15,
	15, 15, 21, 21, 21, 28, 25, 25, 30, 31,
	33, 41,
}

var yyR2 = [...]int8{
	0, 0, 1, 2, 1, 2, 1, 1, 0, 1,
	0, 1, 5, 0, 11, 10, 0, 1, 1, 3,
	0, 1, 1, 1, 0, 1, 3, 4, 7, 0,
	5, 0, 2, 8, 0, 9, 0, 8, 0, 6,
	1, 1, 3, 3, 1, 1, 1, 1, 1, 1,
	2, 2, 1, 3, 1, 4, 4, 2, 4, 1,
	1, 0, 6, 1, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 2, 1,
	2, 1, 1, 0, 1, 1, 3, 1, 1, 2,
	2, 1, 1, 1, 1, 1, 1, 2, 3, 0,
	1, 3, 2, 5, 4, 1, 1, 3, 1, 1,
	1, 1,
}

var yyChk = [...]int16{
	-1000, -34, -1, -35, -3, -2, -36, 8, -11, -6,
	-4, -26, 28, 23, 38, 37, -32, -5, -14, 62,
	24, -21, 50, -22, -19, 12, 17, 26, 29, -13,
	33, 32, 56, 55, 45, 46, 49, 47, -28, 34,
	64, -27, 7, 27, 51, -2, -36, -1, -29, -30,
	-31, 5, 4, 40, 62, 55, 56, 57, 58, 59,
	53, 54, 40, 43, 44, 39, 41, 42, -17, -11,
	8, -17, -10, -17, -11, -28, -41, 67, -11, 18,
	-11, -11, -2, 10, 35, 9, -11, -11, 8, 62,
	62, 65, -18, 62, 33, 8, -9, -3, -11, -10,
	-11, -11, -11, -11, -11, -11, -11, -11, -11, -11,
	-11, -11, -11, 63, -33, 6, -27, 13, 8, 20,
	21, 30, -25, 8, 8, 8, 62, -10, -11, -11,
	-11, 63, -17, -2, 19, -11, -40, -42, -12, -33,
	48, 62, 62, -10, 63, -33, 66, 63, -7, 14,
	-20, -19, -21, 62, 21, -2, -2, -30, 8, -15,
	-16, 8, 25, -15, 63, -11, -8, 15, -11, 21,
	-21, -39, 22, 31, 63, -33, 40, 8, 63, -33,
	16, -2, 13, -38, 63, -2, -12, -16, -14, -12,
	-11, -2, -2, 22, -37, -23, -24, 10, 63, -7,
	22, -23, -2, 10, -25, -2, 11, -25, -30, 36,
	-30,
}

var yyDef = [...]int8{
	-2, -2, -2, -2, 18, 0, 4, 54, 44, 45,
	46, 47, 48, 49, 83, 83, 6, 7, 63, 83,
	0, 79, 0, 81, 82, 0, 0, 0, 16, 0,
	87, 88, 0, 0, 91, 92, 93, 94, 95, 0,
	0, 52, 9, 105, 0, 3, 5, 17, 20, 22,
	23, 108, 109, 0, 83, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 50, 84,
	54, 51, 0, 85, 78, 80, 0, 111, 0, 0,
	0, 0, 0, 0, 0, 0, 89, 90, 102, 83,
	0, 0, 57, 0, 59, 60, 19, 21, 43, 0,
	65, 66, 67, 68, 69, 70, 71, 72, 73, 74,
	75, 76, 77, 64, 83, 110, 53, 16, 0, 0,
	38, 61, 10, 106, 0, 0, 83, 0, 0, 0,
	0, 55, 86, 29, 0, 0, 16, 16, 0, 0,
	11, 99, 99, 0, 104, 0, 56, 58, 31, 0,
	0, 40, 41, 0, 36, 0, 0, 12, 107, 0,
	100, 96, 0, 0, 103, 0, 0, 16, 0, 34,
	0, 16, 39, 62, 10, 0, 0, 97, 10, 0,
	28, 32, 16, 16, 42, 0, 13, 101, 98, 24,
	0, 29, 0, 37, 24, 16, 25, 0, 33, 30,
	35, 16, 0, 0, 0, 0, 15, 0, 26, 14,
	27,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 59, 3, 3,
	62, 63, 57, 55, 6, 56, 67, 58, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 4, 5,
	54, 3, 53, 64, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 65, 3, 66,
}

var yyTok2 = [...]int8{
	2, 3, 7, 8, 9, 10, 11, 12, 13, 14,
	15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
	25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
	35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
	45, 46, 47, 48, 49, 50, 51, 52, 60, 61,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-0 : yypt+1]
//line .\grammar.y:85
		{
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:86
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[1].body, yylex)
			}
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line .\grammar.y:91
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[2].opt_body, yylex)
			}
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:101
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[1].global_variables, yylex)
			}
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:106
		{
			if ast, ok := yylex.(*AstNode); ok {
				ast.ModuleStatement.Append(yyDollar[1].funcProc, yylex)
			}
		}
	case 8:
		yyDollar = yyS[yypt-0 : yypt+1]
//line .\grammar.y:113
		{
			yyVAL.opt_directive = nil
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:114
		{
			yyVAL.opt_directive = &yyDollar[1].token
		}
	case 10:
		yyDollar = yyS[yypt-0 : yypt+1]
//line .\grammar.y:117
		{
			yyVAL.opt_export = nil
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:118
		{
			yyVAL.opt_export = &yyDollar[1].token
		}
	case 12:
		yyDollar = yyS[yypt-5 : yypt+1]
//line .\grammar.y:121
		{
			yyVAL.global_variables = make([]GlobalVariables, len(yyDollar[3].identifiers), len(yyDollar[3].identifiers))
			for i, v := range yyDollar[3].identifiers {
				if yyDollar[1].opt_directive != nil {
					yyVAL.global_variables[i].Directive = yyDollar[1].opt_directive.literal
				}

				yyVAL.global_variables[i].Export = yyDollar[4].opt_export != nil
				yyVAL.global_variables[i].Var = VarStatement{Name: v.literal}
			}
		}
	case 13:
		yyDollar = yyS[yypt-7 : yypt+1]
//line .\grammar.y:134
		{
			isFunction(true, yylex)
		}
	case 14:
		yyDollar = yyS[yypt-11 : yypt+1]
//line .\grammar.y:135
		{
			yyVAL.funcProc = createFunctionOrProcedure(PFTypeFunction, yyDollar[1].opt_directive, yyDollar[3].token.literal, yyDollar[5].declarations_method_params, yyDollar[7].opt_export, yyDollar[9].opt_explicit_variables, yyDollar[10].opt_body)
			isFunction(false, yylex)
		}
	case 15:
		yyDollar = yyS[yypt-10 : yypt+1]
//line .\grammar.y:140
		{
			yyVAL.funcProc = createFunctionOrProcedure(PFTypeProcedure, yyDollar[1].opt_directive, yyDollar[3].token.literal, yyDollar[5].declarations_method_params, yyDollar[7].opt_export, yyDollar[8].opt_explicit_variables, yyDollar[9].opt_body)
		}
	case 16:
		yyDollar = yyS[yypt-0 : yypt+1]
//line .\grammar.y:145
		{
			yyVAL.opt_body = nil
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:146
		{
			yyVAL.opt_body = yyDollar[1].body
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:150
		{
			yyVAL.body = Statements{yyDollar[1].stmt}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:151
		{
			if yyDollar[2].token.literal == ":" && len(yyDollar[1].opt_body) > 0 {
				if _, ok := yyDollar[1].opt_body[len(yyDollar[1].opt_body)-1].(*GoToLabelStatement); !ok {
					yylex.Error("semicolon (;) is expected")
				}
			}
			if yyDollar[3].stmt != nil {
				yyVAL.body = append(yyVAL.body, yyDollar[3].stmt)
			}
		}
	case 20:
		yyDollar = yyS[yypt-0 : yypt+1]
//line .\grammar.y:164
		{
			yyVAL.stmt = nil
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:165
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:168
		{
			yyVAL.token = yyDollar[1].token
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:168
		{
			yyVAL.token = yyDollar[1].token
		}
	case 24:
		yyDollar = yyS[yypt-0 : yypt+1]
//line .\grammar.y:172
		{
			yyVAL.opt_explicit_variables = map[string]VarStatement{}
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:173
		{
			yyVAL.opt_explicit_variables = yyDollar[1].explicit_variables
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:176
		{
			if vars, err := appendVarStatements(map[string]VarStatement{}, yyDollar[2].identifiers); err != nil {
				yylex.Error(err.Error())
			} else {
				yyVAL.explicit_variables = vars
			}
		}
	case 27:
		yyDollar = yyS[yypt-4 : yypt+1]
//line .\grammar.y:183
		{
			if vars, err := appendVarStatements(yyDollar[1].explicit_variables, yyDollar[3].identifiers); err != nil {
				yylex.Error(err.Error())
			} else {
				yyVAL.explicit_variables = vars
			}
		}
	case 28:
		yyDollar = yyS[yypt-7 : yypt+1]
//line .\grammar.y:194
		{
			yyVAL.stmt_if = &IfStatement{
				Expression:  yyDollar[2].stmt,
				TrueBlock:   yyDollar[4].opt_body,
				IfElseBlock: yyDollar[5].opt_elseif_list,
				ElseBlock:   yyDollar[6].opt_else,
			}
		}
	case 29:
		yyDollar = yyS[yypt-0 : yypt+1]
//line .\grammar.y:204
		{
			yyVAL.opt_elseif_list = Statements{}
		}
	case 30:
		yyDollar = yyS[yypt-5 : yypt+1]
//line .\grammar.y:205
		{
			yyVAL.opt_elseif_list = append(yyDollar[5].opt_elseif_list, &IfStatement{
				Expression: yyDollar[2].stmt,
				TrueBlock:  yyDollar[4].opt_body,
			})
		}
	case 31:
		yyDollar = yyS[yypt-0 : yypt+1]
//line .\grammar.y:213
		{
			yyVAL.opt_else = nil
		}
	case 32:
		yyDollar = yyS[yypt-2 : yypt+1]
//line .\grammar.y:214
		{
			yyVAL.opt_else = yyDollar[2].opt_body
		}
	case 33:
		yyDollar = yyS[yypt-8 : yypt+1]
//line .\grammar.y:217
		{
			yyVAL.stmt = TernaryStatement{
				Expression: yyDollar[3].stmt,
				TrueBlock:  yyDollar[5].stmt,
				ElseBlock:  yyDollar[7].stmt,
			}
		}
	case 34:
		yyDollar = yyS[yypt-6 : yypt+1]
//line .\grammar.y:226
		{
			setLoopFlag(true, yylex)
		}
	case 35:
		yyDollar = yyS[yypt-9 : yypt+1]
//line .\grammar.y:226
		{
			yyVAL.stmt_loop = &LoopStatement{
				For:  yyDollar[3].token.literal,
				In:   yyDollar[5].stmt,
				Body: yyDollar[8].opt_body,
			}
			setLoopFlag(false, yylex)
		}
	case 36:
		yyDollar = yyS[yypt-5 : yypt+1]
//line .\grammar.y:234
		{
			setLoopFlag(true, yylex)
		}
	case 37:
		yyDollar = yyS[yypt-8 : yypt+1]
//line .\grammar.y:234
		{
			yyVAL.stmt_loop = &LoopStatement{
				For:  yyDollar[2].stmt,
				To:   yyDollar[4].stmt,
				Body: yyDollar[7].opt_body,
			}
			setLoopFlag(false, yylex)
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:242
		{
			setLoopFlag(true, yylex)
		}
	case 39:
		yyDollar = yyS[yypt-6 : yypt+1]
//line .\grammar.y:242
		{
			yyVAL.stmt_loop = &LoopStatement{
				WhileExpr: yyDollar[2].stmt,
				Body:      yyDollar[5].opt_body,
			}
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:251
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:252
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:253
		{
			yyVAL.stmt = yyDollar[2].stmt
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:257
		{
			yyVAL.stmt = AssignmentStatement{Var: VarStatement{Name: yyDollar[1].token.literal}, Expr: ExprStatements{Statements: Statements{yyDollar[3].stmt}}}
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:258
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:259
		{
			yyVAL.stmt = yyDollar[1].stmt_if
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:260
		{
			yyVAL.stmt = yyDollar[1].stmt_loop
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:261
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:262
		{
			yyVAL.stmt = ContinueStatement{}
			checkLoopOperator(yyDollar[1].token, yylex)
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:263
		{
			yyVAL.stmt = BreakStatement{}
			checkLoopOperator(yyDollar[1].token, yylex)
		}
	case 50:
		yyDollar = yyS[yypt-2 : yypt+1]
//line .\grammar.y:264
		{
			yyVAL.stmt = ThrowStatement{Param: yyDollar[2].stmt}
			checkThrowParam(yyDollar[1].token, yyDollar[2].stmt, yylex)
		}
	case 51:
		yyDollar = yyS[yypt-2 : yypt+1]
//line .\grammar.y:265
		{
			yyVAL.stmt = &ReturnStatement{Param: yyDollar[2].stmt}
			checkReturnParam(yyDollar[2].stmt, yylex)
		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:270
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:271
		{
			yyVAL.stmt = CallChainStatement{Unit: yyDollar[3].stmt, Call: yyDollar[1].stmt}
		}
	case 54:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:277
		{
			yyVAL.stmt = VarStatement{Name: yyDollar[1].token.literal}
		}
	case 55:
		yyDollar = yyS[yypt-4 : yypt+1]
//line .\grammar.y:278
		{
			yyVAL.stmt = MethodStatement{Name: yyDollar[1].token.literal, Param: yyDollar[3].exprs}
		}
	case 56:
		yyDollar = yyS[yypt-4 : yypt+1]
//line .\grammar.y:279
		{
			yyVAL.stmt = ItemStatement{Object: yyDollar[1].stmt, Item: yyDollar[3].stmt}
		}
	case 57:
		yyDollar = yyS[yypt-2 : yypt+1]
//line .\grammar.y:280
		{
			yyVAL.stmt = MethodStatement{Name: yyDollar[1].token.literal, Param: ExprStatements{Statements: Statements{yyDollar[2].stmt}}}
		}
	case 58:
		yyDollar = yyS[yypt-4 : yypt+1]
//line .\grammar.y:281
		{
			yyVAL.stmt = MethodStatement{Name: yyDollar[1].token.literal, Param: ExprStatements{Statements: Statements{yyDollar[3].stmt}}}
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:284
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:285
		{
			yyVAL.stmt = VarStatement{Name: yyDollar[1].token.literal}
		}
	case 61:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:288
		{
			setTryFlag(true, yylex)
		}
	case 62:
		yyDollar = yyS[yypt-6 : yypt+1]
//line .\grammar.y:288
		{
			yyVAL.stmt = TryStatement{Body: yyDollar[2].opt_body, Catch: yyDollar[5].opt_body}
			setTryFlag(false, yylex)
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:294
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:295
		{
			yyVAL.stmt = yyDollar[2].exprs
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:296
		{
			yyVAL.stmt = &ExpStatement{Operation: OpPlus, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:297
		{
			yyVAL.stmt = &ExpStatement{Operation: OpMinus, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 67:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:298
		{
			yyVAL.stmt = &ExpStatement{Operation: OpMul, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:299
		{
			yyVAL.stmt = &ExpStatement{Operation: OpDiv, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:300
		{
			yyVAL.stmt = &ExpStatement{Operation: OpMod, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 70:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:301
		{
			yyVAL.stmt = &ExpStatement{Operation: OpGt, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:302
		{
			yyVAL.stmt = &ExpStatement{Operation: OpLt, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:303
		{
			yyVAL.stmt = &ExpStatement{Operation: OpEq, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 73:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:304
		{
			yyVAL.stmt = &ExpStatement{Operation: OpOr, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:305
		{
			yyVAL.stmt = &ExpStatement{Operation: OpAnd, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:306
		{
			yyVAL.stmt = &ExpStatement{Operation: OpNe, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 76:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:307
		{
			yyVAL.stmt = &ExpStatement{Operation: OpLe, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:308
		{
			yyVAL.stmt = &ExpStatement{Operation: OpGe, Left: yyDollar[1].stmt, Right: yyDollar[3].stmt}
		}
	case 78:
		yyDollar = yyS[yypt-2 : yypt+1]
//line .\grammar.y:309
		{
			yyVAL.stmt = not(yyDollar[2].stmt)
		}
	case 79:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:310
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 80:
		yyDollar = yyS[yypt-2 : yypt+1]
//line .\grammar.y:311
		{
			yyVAL.stmt = GoToStatement{Label: yyDollar[2].goToLabel}
		}
	case 81:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:312
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 82:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:313
		{
			if tok, ok := yyDollar[1].stmt.(Token); ok {
				yyVAL.stmt = tok.literal
			} else {
				yyVAL.stmt = yyDollar[1].stmt
			}
		}
	case 83:
		yyDollar = yyS[yypt-0 : yypt+1]
//line .\grammar.y:322
		{
			yyVAL.stmt = nil
		}
	case 84:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:322
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 85:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:324
		{
			yyVAL.exprs = ExprStatements{Statements: Statements{yyDollar[1].stmt}}
		}
	case 86:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:325
		{
			yyVAL.exprs.Statements = append(yyVAL.exprs.Statements, yyDollar[3].stmt)
		}
	case 87:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:328
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 88:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:329
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 89:
		yyDollar = yyS[yypt-2 : yypt+1]
//line .\grammar.y:330
		{
			yyVAL.stmt = unaryMinus(yyDollar[2].stmt)
		}
	case 90:
		yyDollar = yyS[yypt-2 : yypt+1]
//line .\grammar.y:331
		{
			yyVAL.stmt = yyDollar[2].stmt
		}
	case 91:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:332
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 92:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:333
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 93:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:334
		{
			yyVAL.stmt = yyDollar[1].token.value
		}
	case 94:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:335
		{
			yyVAL.stmt = UndefinedStatement{}
		}
	case 95:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:336
		{
			yyVAL.stmt = yyDollar[1].goToLabel
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:340
		{
			yyVAL.declarations_method_param = *(&ParamStatement{}).Fill(nil, yyDollar[1].token)
		}
	case 97:
		yyDollar = yyS[yypt-2 : yypt+1]
//line .\grammar.y:341
		{
			yyVAL.declarations_method_param = *(&ParamStatement{}).Fill(&yyDollar[1].token, yyDollar[2].token)
		}
	case 98:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:342
		{
			yyVAL.declarations_method_param = *(yyVAL.declarations_method_param.DefaultValue(yyDollar[3].stmt))
		}
	case 99:
		yyDollar = yyS[yypt-0 : yypt+1]
//line .\grammar.y:345
		{
			yyVAL.declarations_method_params = []ParamStatement{}
		}
	case 100:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:346
		{
			yyVAL.declarations_method_params = []ParamStatement{yyDollar[1].declarations_method_param}
		}
	case 101:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:347
		{
			yyVAL.declarations_method_params = append(yyDollar[1].declarations_method_params, yyDollar[3].declarations_method_param)
		}
	case 102:
		yyDollar = yyS[yypt-2 : yypt+1]
//line .\grammar.y:355
		{
			yyVAL.stmt = NewObjectStatement{Constructor: yyDollar[2].token.literal}
		}
	case 103:
		yyDollar = yyS[yypt-5 : yypt+1]
//line .\grammar.y:356
		{
			yyVAL.stmt = NewObjectStatement{Constructor: yyDollar[2].token.literal, Param: yyDollar[4].exprs}
		}
	case 104:
		yyDollar = yyS[yypt-4 : yypt+1]
//line .\grammar.y:357
		{
			yyVAL.stmt = NewObjectStatement{Param: yyDollar[3].exprs}
		}
	case 105:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:362
		{
			yyVAL.goToLabel = &GoToLabelStatement{Name: yyDollar[1].token.literal}
		}
	case 106:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:364
		{
			yyVAL.identifiers = []Token{yyDollar[1].token}
		}
	case 107:
		yyDollar = yyS[yypt-3 : yypt+1]
//line .\grammar.y:365
		{
			yyVAL.identifiers = append(yyVAL.identifiers, yyDollar[3].token)
		}
	case 108:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:368
		{
			yyVAL.token = yyDollar[1].token
		}
	case 109:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:369
		{
			yyVAL.token = yyDollar[1].token
		}
	case 110:
		yyDollar = yyS[yypt-1 : yypt+1]
//line .\grammar.y:370
		{
			yyVAL.token = yyDollar[1].token
		}
	}
	goto yystack /* stack new state and value */
}
